// <auto-generated />
using System;
using HL.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HL.DAL.Migrations
{
    [DbContext(typeof(DataContextClass))]
    partial class DataContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HL.DAL.Model.building_blockclas", b =>
                {
                    b.Property<int>("building_blockclas_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("building_blockclas_Id"), 1L, 1);

                    b.Property<int?>("blockclas_No")
                        .HasColumnType("int");

                    b.HasKey("building_blockclas_Id");

                    b.ToTable("building_blockclas");
                });

            modelBuilder.Entity("HL.DAL.Model.Flore", b =>
                {
                    b.Property<int>("Flore_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flore_Id"), 1L, 1);

                    b.Property<int?>("Flore_No")
                        .HasColumnType("int");

                    b.Property<int?>("block_no")
                        .HasColumnType("int");

                    b.HasKey("Flore_Id");

                    b.ToTable("Flore");
                });

            modelBuilder.Entity("HL.DAL.Model.ImageClass", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Image1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PGAdminId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("ImageTable");
                });

            modelBuilder.Entity("HL.DAL.Model.OTPClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OTPClass");
                });

            modelBuilder.Entity("HL.DAL.Model.PaymentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentsImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentImage");
                });

            modelBuilder.Entity("HL.DAL.Model.PGAdminRegister", b =>
                {
                    b.Property<int>("PGAdmin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PGAdmin_Id"), 1L, 1);

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Is_Auth")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PG_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PG_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Payment_Methods")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role_Id")
                        .HasColumnType("int");

                    b.Property<string>("Select_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select_State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PGAdmin_Id");

                    b.ToTable("PGAdminRegisters");
                });

            modelBuilder.Entity("HL.DAL.Model.PGsheringType", b =>
                {
                    b.Property<int>("Sheretype_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sheretype_Id"), 1L, 1);

                    b.Property<int?>("PGAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharingType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sheretype_Id");

                    b.ToTable("PGsheringType");
                });

            modelBuilder.Entity("HL.DAL.Model.PGTypes", b =>
                {
                    b.Property<int>("PGTypes_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PGTypes_Id"), 1L, 1);

                    b.Property<int?>("PGAdminId")
                        .HasColumnType("int");

                    b.Property<string>("PGtype")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PGTypes_Id");

                    b.ToTable("PGTypes");
                });

            modelBuilder.Entity("HL.DAL.Model.PGUser", b =>
                {
                    b.Property<int>("PGUser_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PGUser_Id"), 1L, 1);

                    b.Property<int?>("Bulding_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Flour_no")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PGAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Room_no")
                        .HasColumnType("int");

                    b.HasKey("PGUser_Id");

                    b.ToTable("PGUserTable");
                });

            modelBuilder.Entity("HL.DAL.Model.PGWorks", b =>
                {
                    b.Property<int>("PGWorks_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PGWorks_Id"), 1L, 1);

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PGAdminId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PGWorks_Id");

                    b.ToTable("PGWorks");
                });

            modelBuilder.Entity("HL.DAL.Model.RegisterClass", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"), 1L, 1);

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_Id")
                        .HasColumnType("int");

                    b.HasKey("Uid");

                    b.ToTable("RegisterTable");
                });

            modelBuilder.Entity("HL.DAL.Model.Room_Sharing", b =>
                {
                    b.Property<int>("Room_Sharing_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Room_Sharing_Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rooms_No")
                        .HasColumnType("int");

                    b.Property<int?>("room_sharing")
                        .HasColumnType("int");

                    b.HasKey("Room_Sharing_Id");

                    b.ToTable("Room_Sharing");
                });

            modelBuilder.Entity("HL.DAL.Model.Rooms", b =>
                {
                    b.Property<int>("Rooms_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rooms_Id"), 1L, 1);

                    b.Property<int?>("Flore_No")
                        .HasColumnType("int");

                    b.Property<int?>("Room_no")
                        .HasColumnType("int");

                    b.HasKey("Rooms_Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HL.DAL.Model.SelectedPGUser", b =>
                {
                    b.Property<int>("SelectedPGUser_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SelectedPGUser_Id"), 1L, 1);

                    b.Property<string>("Cost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PGAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Select_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select_PG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select_PG_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sharing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sharing_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SelectedPGUser_Id");

                    b.ToTable("SelectedPGUser");
                });

            modelBuilder.Entity("HL.DAL.Model.Stetus", b =>
                {
                    b.Property<int>("Stetus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stetus_Id"), 1L, 1);

                    b.Property<int?>("Bulding_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Flour_no")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PGUser_Id")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Room_no")
                        .HasColumnType("int");

                    b.Property<string>("Stetuss")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stetus_Id");

                    b.ToTable("Stetus");
                });

            modelBuilder.Entity("HL.DAL.Model.SuperAdminClass", b =>
                {
                    b.Property<int>("SuperAdmin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperAdmin_id"), 1L, 1);

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hashpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.HasKey("SuperAdmin_id");

                    b.ToTable("SuperAdminClass");
                });

            modelBuilder.Entity("HL.DAL.Model.UserSuggetionCmplet", b =>
                {
                    b.Property<int>("SC_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SC_Id"), 1L, 1);

                    b.Property<int?>("Block_no")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Flour_no")
                        .HasColumnType("int");

                    b.Property<int?>("Room_no")
                        .HasColumnType("int");

                    b.Property<string>("SuggetionOrCmplet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_Id")
                        .HasColumnType("int");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SC_Id");

                    b.ToTable("UserSuggetionCmplet");
                });
#pragma warning restore 612, 618
        }
    }
}
